name: iAuction
main: org.minr.Zaraza107.iAuction.iAuction
version: 2.3b
author: Zaraza107 Nijikokun
description: Auctions for iConomy plugin for Bukkit
commands:
  auction:
    description: Manages auctions
    usage: /<command> help - show auctions help