name: iAuction
main: org.minr.Zaraza107.iAuction.iAuction
version: 2.5
author: Zaraza107
description: Auctions for iConomy plugin for Bukkit
commands:
  auction:
    description: Manages auctions
    usage: /<command> help - show auctions help